USE [master]
GO

/****** Object:  Database [ee_Capital_2013_dev5]    Script Date: 2/20/2017 7:36:33 PM ******/
CREATE DATABASE [ee_Capital_2013_dev5] ON  PRIMARY 
( NAME = N'ee_Capital_2013_dev5', FILENAME = N'G:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ee_Capital_2013_dev5.mdf' , SIZE = 57648640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ee_Capital_2013_dev5_log', FILENAME = N'I:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\ee_Capital_2013_dev5_1.ldf' , SIZE = 1501960KB , MAXSIZE = 51200000KB , FILEGROWTH = 20%)
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ee_Capital_2013_dev5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ARITHABORT ON 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET  MULTI_USER 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ee_Capital_2013_dev5] SET  READ_WRITE 
GO


