//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDev.Web.EmployeeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAll", ReplyAction="http://tempuri.org/IEmployeeService/GetAllResponse")]
        BDev.Common.Employee[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAll", ReplyAction="http://tempuri.org/IEmployeeService/GetAllResponse")]
        System.Threading.Tasks.Task<BDev.Common.Employee[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetByID", ReplyAction="http://tempuri.org/IEmployeeService/GetByIDResponse")]
        BDev.Common.Employee GetByID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetByID", ReplyAction="http://tempuri.org/IEmployeeService/GetByIDResponse")]
        System.Threading.Tasks.Task<BDev.Common.Employee> GetByIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Create", ReplyAction="http://tempuri.org/IEmployeeService/CreateResponse")]
        void Create(BDev.Common.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Create", ReplyAction="http://tempuri.org/IEmployeeService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(BDev.Common.Employee e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Edit", ReplyAction="http://tempuri.org/IEmployeeService/EditResponse")]
        void Edit(BDev.Common.Employee newE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Edit", ReplyAction="http://tempuri.org/IEmployeeService/EditResponse")]
        System.Threading.Tasks.Task EditAsync(BDev.Common.Employee newE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Delete", ReplyAction="http://tempuri.org/IEmployeeService/DeleteResponse")]
        void Delete(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/Delete", ReplyAction="http://tempuri.org/IEmployeeService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : BDev.Web.EmployeeServiceReference.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<BDev.Web.EmployeeServiceReference.IEmployeeService>, BDev.Web.EmployeeServiceReference.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BDev.Common.Employee[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BDev.Common.Employee[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public BDev.Common.Employee GetByID(int ID) {
            return base.Channel.GetByID(ID);
        }
        
        public System.Threading.Tasks.Task<BDev.Common.Employee> GetByIDAsync(int ID) {
            return base.Channel.GetByIDAsync(ID);
        }
        
        public void Create(BDev.Common.Employee e) {
            base.Channel.Create(e);
        }
        
        public System.Threading.Tasks.Task CreateAsync(BDev.Common.Employee e) {
            return base.Channel.CreateAsync(e);
        }
        
        public void Edit(BDev.Common.Employee newE) {
            base.Channel.Edit(newE);
        }
        
        public System.Threading.Tasks.Task EditAsync(BDev.Common.Employee newE) {
            return base.Channel.EditAsync(newE);
        }
        
        public void Delete(int ID) {
            base.Channel.Delete(ID);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int ID) {
            return base.Channel.DeleteAsync(ID);
        }
    }
}
